# ========================================
# | CharacterCards by ShermansWorld      |
# ========================================

# Report bugs at https://github.com/ShermansWorld/CharacterCards

config-version: 1

# =====================================
# |      CHARACTER CARD SETTINGS      |
# =====================================

# Settings for what players can input into their character cards
# Character cards are for enhancing the RPG experience and are purely aesthetic

MinAge: 14
# The minimum age a player can make their character
MaxAge: 120
# The maximum age a player can make their character

# =====================================
# |         INTERACT SETTINGS         |
# =====================================

ShiftRightClick: true
# Displays a player's character card when a player shift + right clicks them

RightClickPaper: true
# Displays a player's character card when a player right clicks them with paper in their hand 