name: CharacterCards
main: me.r0m3x.iccards.Main
version: 1.1
api-version: 1.16
author: Explode
description: CharacterCards

commands:
  character:
    description: Base command
    aliases: [char]
  uuid:
    description: Look at your UUID
  profession:
    description: Shortcut for professions